[package]
name = "ebpf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcc = "0.0.31"
byteorder = "1.4.3"
core_affinity = "0.5.10"
ctrlc = "3.1.9"
libc = "0.2.97"
structopt = "0.3.22"
